/**
 * AI rendering layer — pluggable, and optional.
 *
 * The app is fully usable with no provider configured: the deterministic vector
 * renderer already produces the customer-facing "after" image. This route adds a
 * photoreal pass on top, built from a prompt generated by the design model.
 *
 * To switch it on, set AI_IMAGE_PROVIDER and the matching secret:
 *   wrangler secret put AI_IMAGE_API_KEY
 *
 *   openai      — POST {AI_IMAGE_ENDPOINT|api.openai.com}/v1/images/generations
 *   stability   — Stability AI core endpoint, multipart response
 *   replicate   — Replicate predictions API (async, polled)
 *   custom      — any endpoint that accepts {prompt} and returns {image_b64|url}
 *
 * Adding a provider means adding one function to PROVIDERS below.
 */
import { Hono } from 'hono';
import { uid } from '../../shared/id';
import { buildRenderPrompt } from '../../shared/ai/prompt';
import { loadProject } from '../db';
import type { Env } from '../env';

export const renderings = new Hono<{ Bindings: Env }>();

interface ProviderResult { bytes: Uint8Array; mime: string; meta: Record<string, unknown> }

type Provider = (env: Env, prompt: string, negative: string, basePhoto: Uint8Array | null) => Promise<ProviderResult>;

const b64ToBytes = (b64: string) => {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
};

const PROVIDERS: Record<string, Provider> = {
  async openai(env, prompt) {
    const endpoint = env.AI_IMAGE_ENDPOINT || 'https://api.openai.com/v1/images/generations';
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${env.AI_IMAGE_API_KEY}` },
      body: JSON.stringify({ model: env.AI_IMAGE_MODEL || 'gpt-image-1', prompt, size: '1536x1024', n: 1 }),
    });
    if (!res.ok) throw new Error(`Image provider returned ${res.status}: ${(await res.text()).slice(0, 300)}`);
    const json = await res.json<any>();
    const item = json.data?.[0];
    if (item?.b64_json) return { bytes: b64ToBytes(item.b64_json), mime: 'image/png', meta: { model: env.AI_IMAGE_MODEL || 'gpt-image-1' } };
    if (item?.url) {
      const img = await fetch(item.url);
      return { bytes: new Uint8Array(await img.arrayBuffer()), mime: img.headers.get('content-type') || 'image/png', meta: { url: item.url } };
    }
    throw new Error('Image provider returned no image');
  },

  async stability(env, prompt, negative) {
    const endpoint = env.AI_IMAGE_ENDPOINT || 'https://api.stability.ai/v2beta/stable-image/generate/core';
    const form = new FormData();
    form.set('prompt', prompt);
    form.set('negative_prompt', negative);
    form.set('output_format', 'jpeg');
    form.set('aspect_ratio', '3:2');
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { Authorization: `Bearer ${env.AI_IMAGE_API_KEY}`, Accept: 'image/*' },
      body: form,
    });
    if (!res.ok) throw new Error(`Image provider returned ${res.status}: ${(await res.text()).slice(0, 300)}`);
    return { bytes: new Uint8Array(await res.arrayBuffer()), mime: 'image/jpeg', meta: { provider: 'stability' } };
  },

  async replicate(env, prompt, negative) {
    const create = await fetch('https://api.replicate.com/v1/predictions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${env.AI_IMAGE_API_KEY}`, Prefer: 'wait' },
      body: JSON.stringify({ version: env.AI_IMAGE_MODEL, input: { prompt, negative_prompt: negative, aspect_ratio: '3:2' } }),
    });
    if (!create.ok) throw new Error(`Image provider returned ${create.status}: ${(await create.text()).slice(0, 300)}`);
    const pred = await create.json<any>();
    const url = Array.isArray(pred.output) ? pred.output[0] : pred.output;
    if (!url) throw new Error('Provider returned no output (the model may still be running)');
    const img = await fetch(url);
    return { bytes: new Uint8Array(await img.arrayBuffer()), mime: img.headers.get('content-type') || 'image/png', meta: { predictionId: pred.id } };
  },

  async custom(env, prompt, negative) {
    if (!env.AI_IMAGE_ENDPOINT) throw new Error('AI_IMAGE_ENDPOINT is not set');
    const res = await fetch(env.AI_IMAGE_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...(env.AI_IMAGE_API_KEY ? { Authorization: `Bearer ${env.AI_IMAGE_API_KEY}` } : {}) },
      body: JSON.stringify({ prompt, negative_prompt: negative, model: env.AI_IMAGE_MODEL }),
    });
    if (!res.ok) throw new Error(`Image provider returned ${res.status}: ${(await res.text()).slice(0, 300)}`);
    const json = await res.json<any>();
    if (json.image_b64) return { bytes: b64ToBytes(json.image_b64), mime: json.mime || 'image/png', meta: {} };
    if (json.url) {
      const img = await fetch(json.url);
      return { bytes: new Uint8Array(await img.arrayBuffer()), mime: img.headers.get('content-type') || 'image/png', meta: {} };
    }
    throw new Error('Custom provider must return { image_b64 } or { url }');
  },
};

/** Preview the exact prompt the model produces, without spending anything. */
renderings.get('/projects/:id/render-prompt', async (c) => {
  const project = await loadProject(c.env, c.req.param('id'));
  if (!project) return c.json({ error: 'Project not found' }, 404);
  const variant = Number(c.req.query('variant') || 1);
  const bundle = buildRenderPrompt(project.design, { variant });
  return c.json({ ...bundle, providerConfigured: Boolean(c.env.AI_IMAGE_PROVIDER && PROVIDERS[c.env.AI_IMAGE_PROVIDER]) });
});

renderings.post('/projects/:id/renderings', async (c) => {
  const projectId = c.req.param('id');
  const project = await loadProject(c.env, projectId);
  if (!project) return c.json({ error: 'Project not found' }, 404);

  type RenderBody = { variant?: number; roomStyle?: string; revisionId?: string };
  const body: RenderBody = await c.req.json<RenderBody>().catch(() => ({} as RenderBody));
  const variant = body.variant ?? project.renderings.length + 1;
  const bundle = buildRenderPrompt(project.design, { variant, roomStyle: body.roomStyle });
  const id = uid('rnd');
  const now = new Date().toISOString();
  const providerName = c.env.AI_IMAGE_PROVIDER || '';
  const provider = PROVIDERS[providerName];

  if (!provider) {
    await c.env.DB.prepare(
      'INSERT INTO renderings (id, project_id, variant, status, provider, prompt, error, created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8)',
    ).bind(id, projectId, variant, 'unavailable', providerName || 'none', bundle.prompt,
      'No AI image provider is configured. Set AI_IMAGE_PROVIDER in wrangler.toml and add the AI_IMAGE_API_KEY secret. The vector preview and the drawing set work without it.', now).run();
    return c.json({
      id, variant, status: 'unavailable', url: null, prompt: bundle.prompt, provider: 'none', revisionId: null, createdAt: now,
      error: 'No AI image provider configured — see worker/routes/renderings.ts',
      facts: bundle.facts,
    }, 200);
  }

  try {
    const result = await provider(c.env, bundle.prompt, bundle.negativePrompt, null);
    const photoId = uid('ph');
    let storage = 'd1';
    let storageKey: string | null = null;
    if (c.env.PHOTOS) {
      storage = 'r2';
      storageKey = `${projectId}/${photoId}`;
      await c.env.PHOTOS.put(storageKey, result.bytes, { httpMetadata: { contentType: result.mime } });
    }
    await c.env.DB.batch([
      c.env.DB.prepare(
        'INSERT INTO photos (id, project_id, kind, mime, width, height, caption, storage, storage_key, created_at) VALUES (?1,?2,?3,?4,0,0,?5,?6,?7,?8)',
      ).bind(photoId, projectId, 'after', result.mime, `AI visualisation — variation ${variant}`, storage, storageKey, now),
      ...(storage === 'd1' ? [c.env.DB.prepare('INSERT INTO photo_blobs (photo_id, data) VALUES (?1,?2)').bind(photoId, result.bytes)] : []),
      c.env.DB.prepare(
        'INSERT INTO renderings (id, project_id, variant, status, provider, prompt, photo_id, revision_id, meta_json, created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)',
      ).bind(id, projectId, variant, 'ready', providerName, bundle.prompt, photoId, body.revisionId ?? null, JSON.stringify(result.meta), now),
    ]);
    return c.json({ id, variant, status: 'ready', url: `/api/photos/${photoId}`, prompt: bundle.prompt, provider: providerName, revisionId: body.revisionId ?? null, createdAt: now, facts: bundle.facts });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await c.env.DB.prepare(
      'INSERT INTO renderings (id, project_id, variant, status, provider, prompt, error, created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8)',
    ).bind(id, projectId, variant, 'failed', providerName, bundle.prompt, message, now).run();
    return c.json({ id, variant, status: 'failed', url: null, prompt: bundle.prompt, provider: providerName, error: message, createdAt: now }, 502);
  }
});

renderings.delete('/renderings/:id', async (c) => {
  const id = c.req.param('id');
  const row = await c.env.DB.prepare('SELECT photo_id FROM renderings WHERE id = ?').bind(id).first<{ photo_id: string | null }>();
  const stmts = [c.env.DB.prepare('DELETE FROM renderings WHERE id = ?').bind(id)];
  if (row?.photo_id) {
    stmts.push(c.env.DB.prepare('DELETE FROM photo_blobs WHERE photo_id = ?').bind(row.photo_id));
    stmts.push(c.env.DB.prepare('DELETE FROM photos WHERE id = ?').bind(row.photo_id));
  }
  await c.env.DB.batch(stmts);
  return c.json({ ok: true });
});
